version: '3.8'

services:
  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: Agents
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  #   ports:
  #     - "5432:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 10s
  #     retries: 5

  nats:
    image: nats:alpine3.19
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: unless-stopped
    command: ["-js", "-m", "8222"]

  app:
    build: .
    container_name: collector
    environment:
    #   DATABASE_URL: postgresql://postgres:root@postgres:5432/Agents?sslmode=disable
      NATS_URL: nats://nats:4222
    # depends_on:
      # postgres:
      #   condition: service_healthy
      # nats:
      #   condition: service_healthy
      # nats-setup:
      #   condition: service_completed_successfully
    ports:
      - "8080:8080"

# volumes:
#   postgres_data:
